### ISSUE TITLE
Local flow installation issue

### ISSUE THREAD

**Issue by chrisblossom** [dsilva/webstorm-plugin-flow-typecheck#3]
When running this I am getting the following error:

```
9:04 AM Throwable: flow output was empty
```

Flow is installed locally for the project. I have set my flow locationFlow executable to:

```
/Users/chris/github/app/node_modules/.bin/flow
```

```
Flow: 0.30
Webstorm: 2016.2 EAP 162.1628.41
```

Any ideas what I am doing wrong here? Thank you!

Edit: Looks like using the default install location (installed via brew) works as expected. I would rather keep the install local to each project. Is there something I can do to fix this?

```
/usr/local/bin/flow
```

**Comment by dsilva** [comment]
Hi Chris,

What happens when you run flow in a terminal with that full executable path
from the directory of your JS file for which you saw the error?

Also what happens when you run it with the --json flag?

**Comment by chrisblossom** [comment]
Thanks for the quick response!

``` js
●  pwd
/Users/chris/github/app/src/helpers
●  /Users/chris/github/app/node_modules/.bin/flow time.js
No errors!
●  /Users/chris/github/app/node_modules/.bin/flow --json time.js
{"flowVersion":"0.30.0","errors":[],"passed":true}%
```

Is that what you are asking for?

**Comment by dsilva** [comment]
Thanks for that.  The "output was empty" error happens when the output of this is empty:

```
cd /Users/chris/github/app/src/helpers && cat time.js | /Users/chris/github/app/node_modules/.bin/flow check-contents --show-all-errors --json time.js
```

I'll add some more debug output around how exactly the plugin executed flow in that scenario so we can narrow it down to something reproducible.

**Comment by dsilva** [comment]
Can you please try https://github.com/dsilva/webstorm-plugin-flow-typecheck/releases/tag/1.2.2 ?  It will log more information than just "flow output was empty" now.

**Comment by chrisblossom** [comment]
Looks like that issue has been fixed but another one came up. It is unable to find node. I use [tj/n](https://github.com/tj/n) to manage my node installations, so the path is `~/n/bin/node`. Looking at my eslint config it is pulling that information from a Node interpreter option from "Project". Most likely set in `Languages & Frameworks > Node.js and NPM`. I'd guess nvm has the same issue.

If you ned anymore information let me know.

```
flow output was empty.
Working directory: /Users/chris/github/app/src/helpers
File: /Users/chris/github/app/src/helpers/time.js
Command: [/Users/chris/github/app/node_modules/.bin/flow, check-contents, --show-all-errors, --json, time.js]
Exit code: 127
stderr: env: node: No such file or directory

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
    at com.github.dsilva.flowtc.TypeCheck.flowCheck(TypeCheck.java:166)
    at com.github.dsilva.flowtc.TypeCheck.errors(TypeCheck.java:65)
    at com.github.dsilva.flowtc.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:55)
    at com.github.dsilva.flowtc.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:14)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.b(ExternalToolPass.java:212)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
    at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:260)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:274)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:229)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
    at com.intellij.util.Alarm$Request.run(Alarm.java:389)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
    at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by vertiman** [comment]
I'm having the same issue as chris above.  Not really sure what's going on, or why node is being invoked at all in the process?  Happy to help troubleshoot.

**Comment by dsilva** [comment]
That's because node_modules/.bin/flow is a symlink to node-modules/flow-bin/cli.js which looks like this:

```
#!/usr/bin/env node
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */
'use strict';
var spawn = require('child_process').spawn;

var input = process.argv.slice(2);
var bin = require('./');

spawn(bin, input, {stdio: 'inherit'})
    .on('exit', process.exit);
```

It invokes /usr/bin/env to invoke node, to then load flow-bin/cli.js, which loads flow-bin/index.js, which loads flow-bin/lib/index.js, which loads and calls bin-wrapper to download and/or execute flow.

I guess node is not in your $PATH as seen by child processes of your IDE.  In Chris's case, how does node-modules/bin/.flow find node if ~/n/bin is not in your $PATH?

As a quick workaround, you can point the plugin at a wrapper script that sets up PATH before calling node-modules/bin/.flow.  If that's annoying, we can potentially have the plugin try to find the node interpreter directory from the IDE settings.  I don't know if plugins have access to that though.

**Comment by vertiman** [comment]
I fixed it temporarily locally by changing the node at the top of cli.js to
use my absolute path to node (inside the ~/n/bin directory).  It does
appear that if you want a path to be passed to the child processes, you
need to do it explicitly in the runtime.exec() call, otherwise no path is
passed through.

It should be noted that flow works properly if run from the command line,
because the PATH is setup correctly via bash/terminal.  It’s just not set
properly for OSX Applications and their children.
